name: ctrlx-postgresql
version: "2.2.0"
grade: stable
summary: PostgreSQL object-relational database for ctrlX OS.
description: |  
    PostgreSQL is a robust and extensible open-source relational 
    database management system. It is known for its reliability, scalability, 
    and compliance with SQL standards. It supports a variety of data types, 
    indexing methods, and other advanced features.
base: core22
confinement: strict
# architectures:
   # - build-on: [amd64]
   #  build-for: [arm64]  ### <------ CHANGE IF NEEDED

apps: 
    ctrlx-postgresql:
        command: bin/run.sh 
        plugs: [network, network-bind, mount-observe, network-observe, system-observe, active-solution]
        daemon: simple
        passthrough:
          restart-condition: always
          restart-delay: 10s   

parts:
    postgresql:
        plugin: nil
        stage-packages:
            - postgresql
            - libssl-dev
            - libcurl4-openssl-dev
   
    shscripts:  
        source: ./shscripts/
        plugin: dump
        organize:
          '*': bin/

    # Neccesary to embed additional files
    configs:
        source: ./configs
        plugin: dump
        organize:
           'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/

slots:
  # Allow the snap files to be available outside it
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
        - $SNAP/package-assets/${SNAPCRAFT_PROJECT_NAME}

plugs:
  # Allow read the ctrlX OS memory with the right persmisions
  active-solution:
    interface: content
    content: solutions
    target: $SNAP_COMMON/solutions

hooks:
  # Automatically used when the snap connects the plug
  connect-plug-active-solution:
    plugs: [active-solution]