name: ctrlx-mongodb
version: "2.2.0"
grade: stable
summary: MongoDB document-oriented database for ctrlX OS.
description: |  
    MongoDB is a high-performance, open source, schema-free
    document-oriented data store that's easy to deploy, manage
    and use. It's network accessible, written in C++ and offers 
    the following features.

       * Collection oriented storage - easy storage of object-style data
       * Full index support, including on inner objects
       * Query profiling
       * Replication and fail-over support
       * Efficient storage of binary data including large objects (e.g. videos)
       * Auto-sharding for cloud-level scalability

    High performance, scalability, and reasonable depth of functionality
    are the goals for the project.
base: core22
confinement: strict
# architectures:
   # - build-on: [amd64]
   #  build-for: [arm64]  ### <------ CHANGE IF NEEDED

apps: 
    ctrlx-mongodb:
        command: bin/run.sh 
        plugs: [network, network-bind, mount-observe, network-observe, system-observe, active-solution]
        daemon: simple
        passthrough:
          restart-condition: always
          restart-delay: 10s   

parts:
    mongodb:
        plugin: nil
        stage-packages:
            - mongodb-org-server
            - mongodb-org-mongos
            - mongodb-mongosh
            - libssl-dev
            - libcurl4-openssl-dev
   
    shscripts:  
        source: ./shscripts/
        plugin: dump
        organize:
          '*': bin/

    configs:
        source: ./configs
        plugin: dump
        organize:
           'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/

slots:
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
        - $SNAP/package-assets/${SNAPCRAFT_PROJECT_NAME}

plugs:
  active-solution:
    interface: content
    content: solutions
    target: $SNAP_COMMON/solutions

hooks:
  connect-plug-active-solution:
    plugs: [active-solution]