#!/bin/sh

echo "running the hook"

MY_FOLDERNAME=ctrlx-postgresql
MYDIR="$SNAP_DATA/$MY_FOLDERNAME"

mkdir -p $MYDIR
chown -R root "$MYDIR"

mkdir /var/run_v2/postgresql/14-main.pg_stat_tmp
 
cp -r $SNAP/bin/data/configuration $MYDIR/configuration
cp -r $SNAP/bin/data/data_postgresql $MYDIR/data_postgresql

chmod 777 -R "$MYDIR/configuration"
chmod 750 -R "$MYDIR/data_postgresql"

chown -R snap_daemon "$MYDIR"
chown -R snap_daemon "/var/run_v2/postgresql"

echo "hook finished"
